# Generated by Django 4.2.4 on 2023-09-01 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_menu_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('items', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='rating',
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_name',
            field=models.TextField(max_length=500),
        ),
    ]
